apiVersion: v1
kind: Secret
metadata:
  name: lab-user-jwt
  namespace: simple-api
  labels:
    konghq.com/credential: jwt
stringData:
  key: lab-user-key
  algorithm: HS256
  secret: CHANGE-ME-IN-YOUR-LAB-TO-A-LONG-RANDOM-SECRET
